# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

repos:
  - repo: https://github.com/google/addlicense
    rev: v1.2.0-rc0
    hooks:
      - id: addlicense
        args: ["-f", "bin/_license.txt"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^tests/.*/fixtures/.*
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        exclude: ^tests/.*/fixtures/.*
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
  - repo: local
    hooks:
      - id: uv-lock
        name: Generate uv lock files for projects
        entry: ./bin/_uv_lock.sh
        language: script
        files: pyproject\.toml$
      - id: uv-lock-script
        name: Generate uv lock files for scripts
        entry: ./bin/_uv_lock_script.sh
        language: script
        types: [python]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.12.2 # DO NOT UPDATE UNTIL https://github.com/tcort/markdown-link-check/pull/452 IS MERGED
    hooks:
      - id: markdown-link-check
        args: [--config, ".link-check.json", --quiet]
        stages: [manual]
